Soal 1
Menurut sumber yang saya baca dari Binus University School of Conputer Science yang ditulis oleh Muhammad Ikhwan Jambak, software engineering pada tahap implementasi memerlukan test atauupun pengujian. Pengujian perangkat lunak (software testing) adalah bagian integral dari sebuah pembangunan perangkat lunak (software development). Sering kali, pembangunan sebuah perangkat lunak disempitkan dengan pengkodean (coding) atau pemograman dan pengujian perangkat lunak adalah salah satu proses vital dalam pembangunan perangkat lunak yang sering diabaikan. Padahal proses ini sangat penting, terutama untuk pembangunan perangkat lunak yang akan diproduksi secara masal (mass production), yang menuntut adanya jaminan mutu dan bebas kesalahan (bug-free) sebelum masuk pada tahap produksi. Dapat dikatakan bahwa tujuan utama pengujian perangkat lunak adalah untuk memastikan tidak ada kesalahan dan sesuai dengan ekspektasi yang diharapkan yang tertuang dalam rencana dan perancangan yang telah dibuat dan disetujui sebelumnya.
Menurut buku Software Engineering Body of Knowledge Chapter 4, Pengujian adalah proses yang digunakan untuk membantu mengidentifikasi kebenaran, kelengkapan dan kualitas perangkat lunak komputer yang dikembangkan. Pengujian perangkat lunak adalah menjalankan perangkat lunak dalam lingkungan simulasi atau nyata, menggunakan input yang dipilih dengan cara yang ditentukan. Dengan kata sederhana, pengujian perangkat lunak adalah kegiatan untuk memeriksa apakah sistem perangkat lunak bebas cacat. Pengujian pada perangkat lunak ini dimaksudkan untuk mendeteksi kesalahan sehingga produk dapat diperbaiki sebelum rilis ke pengguna akhir. Dalam istilah sederhana, pengujian perangkat lunak adalah kegiatan untuk melihat bahwa sistem perangkat lunak bebas dari cacat. Kasus perangkat lunak pada dasarnya terdiri dari tiga komponen, yaitu persyaratan masukan, persyaratan keluaran, dan sistem yang bersangkutan
Berdasarkan beberapa sumber yang sudah saya baca, saya menyimpukan bahwa software engineer pada tahap implementasi wajib melakukan pengujian test.
Menurut saya pengujjian perangkat lunak sangatlah penting. Hal itu untuk memastikan bahwa software yang kita hasilkan sesuai dengan kebutuhan yang sudah kita tentukan. Selain itu juga  untuk menghindari resiko kegagalan yang ditimbulkan oleh perangkat lunak.
Software pengujian membantu menyelesaikan aplikasi perangkat lunak atau produk terhadap bisnis dan kebutuhan pengguna. Hal ini sangat penting untuk memiliki cakupan tes yang baik untuk menguji aplikasi perangkat lunak sepenuhnya dan membuatnya yakin bahwa itu bekerja dengan baik dan sesuai dengan spesifikasinya.
 
Soal  2
Menurut sumber yang saya baca dari Glints.com yang ditulis oleh Humaira Aliya,
Tujuan utama system integration testing adalah untuk menguji otomatisasi dari gabungan komponen yang ada, serta ketergantungan antara satu sama lain. Intinya, SIT berfokus pada mengecek interaksi dan interface dari tiap sistem yang ada.  Pengujian ini dibutuhkan untuk membangun program sekaligus mencari tahu apakah ada kesalahan dalam interface. Pengujian ini mengecek ketergantungan di dalam sebuah rangkaian sistem. Maka dari itu, prosesnya pun jadi lebih sederhana. Pasalnya, terdapat banyak sekali komponen dan sistem yang ada. Dengan mengikuti setiap rangkaiannya, pengujian jadi lebih teratur dan tidak berbelit-belit. Sistem lain yang bisa diintegrasikan atau digabungkan juga bisa saja eksternal, yang berarti dikembangkan oleh pihak luar. Biasanya sistem tersebut bisa didapatkan melalui application programming interface (API) atau microservice.
Menurut sumber yang saya baca dari Guru99.com yang ditulis oleh Thomas Hamilton
Unit Test adalah jenis pengujian perangkat lunak di mana unit individu atau komponen perangkat lunak diuji. Tujuannya adalah untuk memvalidasi bahwa setiap unit kode perangkat lunak berfungsi seperti yang diharapkan. Pengujian Unit dilakukan selama pengembangan (fase pengkodean) aplikasi oleh pengembang. Tes Unit mengisolasi bagian kode dan memverifikasi kebenarannya. Sebuah unit dapat berupa fungsi individu, metode, prosedur, modul, atau objek. Mengapa harus melakukan unit test ? hal itu penting karena pengembang perangkat lunak terkadang mencoba menghemat waktu melakukan pengujian unit minimal dan ini adalah mitos karena pengujian unit yang tidak tepat menyebabkan biaya tinggi untuk memperbaiki Cacat selama Pengujian Sistem , Pengujian Integrasi , dan bahkan Pengujian Beta setelah aplikasi dibangun. Jika pengujian unit yang tepat dilakukan dalam pengembangan awal, maka pada akhirnya akan menghemat waktu dan uang.
Berdasarkan beberapa sumber yang sudah saya baca mengenai pentingnya melakukan Unit Test dan Integration Test pada tahap implementasi, Menurut saya sangat penting untuk melakukan unit test dan integration test pada tahap implementasi karena pada tahap ini kita akan memeriksa apakah sistem perangkat lunak yang kita bangun sudah bebas dari cacat atau dengan kata lain kita bisa mendeteksi kesalahan sehingga produk bisa diperbaiki sebelum rilis ke pengguna akhir.
Jika dua test ini tidak dilakukan dampak atau kemungkinan terburuk yang mungkin akan terjadi adalah kita tidak mengetahui apakah sistem perangkat lunak yang kita bangun apakah sudah bekerja dengan benar tanpa adanya bug atau kah sebaliknya ? dengan kata lain resiko kegagalan dalam membangun aplikasi tersebut sangat besar.
 
Soal 3
Menurut sumber yang saya baca dari blog.skillacademy.com dari Ruangguru
Quality Assurance adalah serangkaian proses sistematis untuk menentukan apakah suatu produk atau jasa memenuhi syarat yang ditentukan. QA menentukan dan menetapkan persyaratan untuk membuat atau mengembangkan produk tertentu agar memiliki kualitas yang baik.
Quality Assurance menggunakan pendekatan proses untuk mencegah cacat produk. Karena itu biasanya QA juga melakukan monitoring pembuatan produk mulai dari tahap perencanaan sampai pengujian. Ini dilakukan untuk mengurangi rework (pengerjaan ulang) agar proses kerja efisien dan menghindari keluhan dari konsumen.
Menurut sumber yang saya baca dari ruanguji.quora.com
Software Testing itu adalah satu bidang atau bagian dari tahapan pembangunan atau pengembangan suatu perangkat lunak yang khusus untuk melakukan pengujian suatu perangkat lunak yang sedang dibangun atau dikembangkan.Software Quality Assurance atau SQA adalah sebuah proses yang dilakukan untuk memastikan atau meyakinkan bahwa semua proses atau aktivitas dalam pembangunan atau pengembangan perangkat lunak berjalan sesuai dengan standard atau ketentuannya.Ketentuan atau standard ini beragam, tidak semua lingkungan pekerjaan menerapkan standard yang sama . Semua tergantung aturan main dari masing masing team, divisi atau bahkan perusahaan.
Menurut sumber yang saya baca dari share.its.ac.id
QA engineer lebih fokus pada bagaimana proses pengembangan perangkat lunak dilakukan dengan baik daripada bagaimana hasil akhir perangkat lunak yang dihasilkan. Tugas QA engineer memastikan setiap proses pengembangan perangkat lunak berjalan dengan baik guna menjaga kualitas pengembangan perangkat lunak. Menjaga kualitas proses programming dan build/test menjadi salah satu fokus utama pada pekerjaan QA engineer.
Berbeda dengan QA engineer, QA tester lebih berfokus kepada kualitas perangkat lunak yang digunakan. Pengujian-pengujian yang dilakukan oleh QA tester lebih fokus pada metode black-box. QA tester bertugas memastikan perangkat lunak yang di hasilkan sudah sesuai dengan keinginan user.
Berdasarkan beberapa sumber yang sudah saya baca, Menurut saya pekerjaan sebagai QA Engineer dan Software Engineer yang melakukan testing memiliki tugas yang berbeda. Software testing fokus pengujiannya yaitu produknya atau perangkat lunaknya, sedangkan QA berfokus pada seluruh kegiatan, proses , aktivitas, bahkan metode yang digunakan dalam pembangunan dan pengembangan perangkat lunak termasuk fase testing. Menurut beberapa sumber yang say abaca QA Engineer harus memastikan semua proses,yaitu proses SDLC( Software Development Life Cycle ) atau Daur hidup atau siklus pengembangan perangkat lunak. Semua tahapan pada pembangunan atau perangkat lunak di setiap divisi/team pasti sudah ada standard atau prosedurnya masing-masing.

 
Soal 4
Menurut sumber yang saya baca dari https://www.dictio.id/, Software Testing atau Pengujian perangkat lunak merupakan suatu proses investigasi yang dilakukan untuk mendapatkan informasi mengenai kualitas dari suatu produk atau layanan yang sedang diuji, atau lebih spesifiknya software testing adalah proses mengeksekusi suatu program untuk menemukan bug (kesalahan atau cacat lainnya) dari perangkat lunak.
Dapat disimpulkan apabila perangkat lunak tidak dilakukan test maka terdapat bug dalam perangkat lunak tersebut. Akan tetapi walaupun tidak semua test yang dapat dilakukan, mungkin beberapa test yang dianggap lebih penting mungkin seperti keamanan dan business logic dapat kita lakukan agar aplikasi dapat berjalan sesuai dengan yang diinginkan dan berfungsi sebagaimana semestinya.

 
Soal 5
Menurut sumber yang saya baca dari socs.binus.ac.id yang ditulis oleh IRMA KARTIKA WAIROOY, S.KOM., M.TI
Strategi software testing dapat dilakukan secara manual atau otomatis. Menurut strategi pengujian manual, pendekatan yang lebih tradisional, penguji menyiapkan suite tes yang menurut mereka akan lebih baik menjalankan program. Alat pengujian perangkat lunak otomasi membantu dalam menghasilkan kasus uji dari spesifikasi program atau dari data teks aslinya. Pengujian manual adalah teknik pengujian di mana insinyur penguji menyiapkan test case secara manual dan mengeksekusinya untuk mengidentifikasi cacat pada perangkat lunak. Mengotomatiskan pengujian perangkat lunak menggunakan bahasa scripting seperti Python, JavaScript atau Tool Command Language karena kasus uji dapat dengan mudah dieksekusi oleh mesin dengan sedikit intervensi manusia dan perhatian.
Menurut sumber yang saya baca dari medium.com
1.	Manual Testing
Pengujian manual adalah pengujian yang dilakukan secara manual oleh QA. Dalam pengujiannya QA memeriksa semua fitur pada software , untuk memastikan ada atau tidaknya bug dalam software. Biasanya pengujian secara manual dilakukan tanpa bantuan dari tools automated test. Manual testing berperan penting saat pengujian visual dimana automation tools tidak dapat melakukan.
2.	Automated Testing
Automated test bergantung pada pra-scripted tes yang berjalan secara otomatis, fungsinya untuk membandingkan hasil yang diharapkan dengan hasil yang sebenarnya. Sehingga dapat mengetahui apakah aplikasi berjalan sesuai dengan apa yang diharapkan, menggunakan automated testing dapat dilakukan secara berulang. Pada automation testing dibutuhkan tools untuk melakukan pengujiannya,seperti Selenium IDE .
Berdasarkan beberapa sumber yang sudah saya baca,  Menurut saya Testing perangkat secara manual mungkin memakan banyak waktu yang cukup lama, ditambah apabila fitur perangkat lunak yang sangat kompleks. Akan tetapi jika dibanding dengan automated testing, manual testing jauh lebih mudah. Kita tidak perlu menggunakan peralatan tambahan atau bahkan membuat teks coding seperti yang biasa digunakan dalam metode automated testing. Quality Assurance tester hanya perlu membuka software melalui device untuk melakukan proses testing.
Walaupun begitu akan tetap ada kelebihan dan kekurangannya masing-masing saat menggunakan manual testing ataupun automated testing.
Menurut saya, Manual Testing tetap perlu dilakukan. Karna peran penting manual testing tidak bisa digantikan dengan Automation Testing atau pengujian secara otomatis oleh bantuan software testing. Terdapat beberapa aspek yang hanya bisa dilakukan dengan cara berperan sebagai end user, seperti User Interface / User Experience (UI/UX). Automation testing tidak akan bisa melakukan pengujian kesesuaian interface, warna, experience pengguna dan sebagainya. Manual testing memfasilitasi Quality Assurance tester untuk menemukan bug ketika berinteraksi dengan faktor UI & UX. Ketika harus  Maka dari itu, Quality Assurance tester dapat memberikan  mereka mengenai tampilan dari software.


